# Generated by Django 4.1.7 on 2023-04-16 05:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='first name')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('enrollmentno', models.IntegerField(verbose_name='roll no')),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('present', models.BooleanField(default=False, verbose_name='Present')),
                ('image', models.ImageField(upload_to='profilepic')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='MentorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Mentor name')),
                ('phone', models.BigIntegerField(verbose_name='Phone no')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'db_table': 'Mentor_Detail',
            },
        ),
    ]
