# Generated by Django 4.1.7 on 2023-04-16 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.studentdetail'),
        ),
    ]
