# Generated by Django 4.1.7 on 2023-04-18 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_present_studentdetail_is_present_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(null=True, to='core.studentdetail', verbose_name='students detail'),
        ),
    ]
