# Generated by Django 4.1.7 on 2023-04-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studentdetail_date_alter_subject_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(to='core.studentdetail', verbose_name='students detail'),
        ),
    ]
