# Generated by Django 4.1.7 on 2023-04-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_professordetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professordetail',
            name='password',
        ),
        migrations.RemoveField(
            model_name='professordetail',
            name='username',
        ),
    ]
