# Generated by Django 4.1.7 on 2023-04-30 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_professordetail_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student', models.ManyToManyField(to='core.studentdetail', verbose_name='students detail')),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.AlterField(
            model_name='professordetail',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
