# Generated by Django 4.1.7 on 2023-04-30 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_course_alter_professordetail_subject_delete_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professordetail',
            name='subject',
        ),
        migrations.AddField(
            model_name='professordetail',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
    ]
