# Generated by Django 4.1.7 on 2023-04-30 11:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_professordetail_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professordetail',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(null=True, to='core.studentdetail', verbose_name='students detail'),
        ),
        migrations.AlterField(
            model_name='professordetail',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
    ]
