# Generated by Django 4.1.7 on 2023-05-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_course_student_studentdetail_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='date',
            field=models.DateField(auto_now_add=True, unique_for_date=True, verbose_name='Date'),
        ),
    ]
