# Generated by Django 4.1.7 on 2023-05-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_studentdetail_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
    ]
