# Generated by Django 4.1.7 on 2023-05-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_studentdetail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
